language: node_js
node_js:
- 10.16.0
cache:
  directories:
  - node_modules
script:
- yarn build
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: heroku
  api_key:
    secure: "5df973ce-392c-4bcf-939d-71bda38f6d81"
  app: transport-networks