export const SET_SCROLL = "SET_SCROLL"
export const ADD_TRIGGER = "ADD_TRIGGER"
export const REMOVE_TRIGGER = "REMOVE_TRIGGER"

export const FETCH_DATA_START = "FETCH_DATA_START"
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS"
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR"

export const FETCH_STOPS_START = "FETCH_STOPS_START"
export const FETCH_STOPS_SUCCESS = "FETCH_STOPS_SUCCESS"
export const FETCH_STOPS_ERROR = "FETCH_STOPS_ERROR"
export const REMOVE_DEGREE_TWO_NODE = "REMOVE_DEGREE_TWO_NODE"
