export const FETCH_STOPS_START = "FETCH_STOPS_START"
export const FETCH_STOPS_SUCCESS = "FETCH_STOPS_SUCCESS"
export const FETCH_STOPS_ERROR = "FETCH_STOPS_ERROR"

export const FETCH_STATION_TYPES_START = "FETCH_STATION_TYPES_START"
export const FETCH_STATION_TYPES_SUCCESS = "FETCH_STATION_TYPES_SUCCESS"
export const FETCH_STATION_TYPES_ERROR = "FETCH_STATION_TYPES_ERROR"
