export const ADD_TRIGGER = "ADD_TRIGGER"
export const REMOVE_TRIGGER = "REMOVE_TRIGGER"

export const FETCH_ROUTES_START = "FETCH_ROUTES_START"
export const FETCH_ROUTES_SUCCESS = "FETCH_ROUTES_SUCCESS"
export const FETCH_ROUTES_ERROR = "FETCH_ROUTES_ERROR"
